-- Made with 'mini.colors' module of https://nvim-mini.org/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "gnome"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.documentation", { link = "@comment" })
hi(0, "@comment.error", { link = "@text.danger" })
hi(0, "@comment.note", { link = "@text.note" })
hi(0, "@comment.todo", { link = "@text.todo" })
hi(0, "@comment.warning", { link = "@text.warning" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@debug", { link = "Debug" })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@exception", { link = "Exception" })
hi(0, "@field", { link = "Identifier" })
hi(0, "@float", { link = "Float" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@function.method", { link = "@method" })
hi(0, "@function.method.call", { link = "@method.call" })
hi(0, "@include", { link = "Include" })
hi(0, "@keyword.conditional", { link = "@keyword" })
hi(0, "@keyword.conditional.ternary", { link = "Keyword" })
hi(0, "@keyword.coroutine", { link = "@keyword" })
hi(0, "@keyword.debug", { bold = true, fg = "#b3ffe9" })
hi(0, "@keyword.directive", { bold = true, fg = "#a1c3ff" })
hi(0, "@keyword.directive.define", { link = "@keyword.directive" })
hi(0, "@keyword.exception", { link = "@keyword" })
hi(0, "@keyword.function", { link = "@keyword" })
hi(0, "@keyword.import", { bold = true, fg = "#a1c3ff" })
hi(0, "@keyword.operator", { link = "@keyword" })
hi(0, "@keyword.repeat", { link = "@keyword" })
hi(0, "@keyword.return", { bold = true, fg = "#ffbda5" })
hi(0, "@keyword.storage", { bold = true, fg = "#ffffff" })
hi(0, "@lsp.mod.deprecated", { fg = "#ffbada" })
hi(0, "@lsp.type.class", { link = "@structure" })
hi(0, "@lsp.type.decorator", { link = "@function" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.macro", { link = "@macro" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.struct", { link = "@structure" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@macro", { link = "Macro" })
hi(0, "@markup.environment", { link = "@module" })
hi(0, "@markup.heading", { link = "@text.title" })
hi(0, "@markup.heading.1", { fg = "#ffbda5" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bold = true, fg = "#626266" })
hi(0, "@markup.heading.2", { fg = "#ffe1a6" })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bold = true, fg = "#626266" })
hi(0, "@markup.heading.3", { fg = "#e0ffbb" })
hi(0, "@markup.heading.4", { fg = "#b3ffe9" })
hi(0, "@markup.heading.4.vimdoc", { link = "Title" })
hi(0, "@markup.heading.5", { fg = "#a3ebff" })
hi(0, "@markup.heading.6", { fg = "#a1c3ff" })
hi(0, "@markup.italic", { link = "@text.emphasis" })
hi(0, "@markup.link", { link = "@text.reference" })
hi(0, "@markup.link.label", { link = "@markup.link" })
hi(0, "@markup.link.url", { fg = "#ffffff", underline = true })
hi(0, "@markup.list", { link = "@punctuation.special" })
hi(0, "@markup.list.checked", { link = "DiagnosticOk" })
hi(0, "@markup.list.unchecked", { link = "DiagnosticWarn" })
hi(0, "@markup.math", { link = "@string.special" })
hi(0, "@markup.quote", { link = "@string.special" })
hi(0, "@markup.raw", { link = "@text.literal" })
hi(0, "@markup.raw.block", { link = "@markup.raw" })
hi(0, "@markup.strikethrough", { link = "@text.strike" })
hi(0, "@markup.strong", { link = "@text.strong" })
hi(0, "@markup.underline", { link = "@text.underline" })
hi(0, "@method", { link = "Function" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@module", { link = "@namespace" })
hi(0, "@module.builtin", { link = "@variable.builtin" })
hi(0, "@namespace", { link = "Identifier" })
hi(0, "@number.float", { link = "@float" })
hi(0, "@parameter", { fg = "#a1c3ff" })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@punctuation.bracket", { link = "@punctuation" })
hi(0, "@punctuation.delimiter", { link = "@punctuation" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string.documentation", { link = "@string" })
hi(0, "@string.escape", { link = "SpecialChar" })
hi(0, "@string.regexp", { link = "SpecialChar" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.path", { link = "Directory" })
hi(0, "@string.special.symbol", { link = "@constant" })
hi(0, "@string.special.url", { link = "@markup.link.url" })
hi(0, "@string.special.vimdoc", { link = "@constant" })
hi(0, "@structure", { link = "Structure" })
hi(0, "@symbol", { link = "Keyword" })
hi(0, "@tag.attribute", { link = "@tag" })
hi(0, "@tag.delimiter", { link = "@punctuation" })
hi(0, "@text.danger", { link = "ErrorMsg" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.literal", { link = "Special" })
hi(0, "@text.note", { link = "MoreMsg" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@text.warning", { link = "WarningMsg" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@type.qualifier", { link = "StorageClass" })
hi(0, "@variable", { fg = "#ffffff" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@variable.member", { link = "@field" })
hi(0, "@variable.parameter", { link = "@parameter" })
hi(0, "Added", { fg = "#e0ffbb" })
hi(0, "Beacon", { bg = "#ffffff" })
hi(0, "Bold", { bold = true })
hi(0, "BqfPreviewFloat", { link = "NormalFloat" })
hi(0, "BqfPreviewTitle", { link = "FloatTitle" })
hi(0, "BqfSign", { fg = "#b3ffe9" })
hi(0, "BufferCurrent", { bg = "#1c1c1f", bold = true, fg = "#bfbcff" })
hi(0, "BufferCurrentIcon", { bg = "#1c1c1f" })
hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
hi(0, "BufferCurrentMod", { bg = "#3e3e41", bold = true, fg = "#bfbcff" })
hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
hi(0, "BufferCurrentTarget", { bg = "#626266", bold = true, fg = "#bfbcff" })
hi(0, "BufferInactive", { bg = "#121215", fg = "#ffffff" })
hi(0, "BufferInactiveIcon", { bg = "#121215" })
hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
hi(0, "BufferInactiveMod", { bg = "#3e3e41", fg = "#ffffff" })
hi(0, "BufferInactiveSign", { link = "BufferInactive" })
hi(0, "BufferInactiveTarget", { bg = "#626266", fg = "#ffffff" })
hi(0, "BufferLineBuffer", { fg = "#adadad" })
hi(0, "BufferLineBufferSelected", { bold = true, fg = "#ffffff" })
hi(0, "BufferLineBufferVisible", { fg = "#ffffff" })
hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
hi(0, "BufferLineFill", { link = "Normal" })
hi(0, "BufferLineTab", { bg = "#e0ffbb", fg = "#1c1c1f" })
hi(0, "BufferLineTabSelected", { bg = "#e0ffbb", bold = true, fg = "#1c1c1f" })
hi(0, "BufferOffset", { link = "Normal" })
hi(0, "BufferTabpageFill", { link = "Normal" })
hi(0, "BufferTabpages", { bg = "#e0ffbb", bold = true, fg = "#1c1c1f" })
hi(0, "BufferVisible", { bg = "#1c1c1f", bold = true, fg = "#ffffff" })
hi(0, "BufferVisibleIcon", { bg = "#1c1c1f" })
hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
hi(0, "BufferVisibleMod", { bg = "#3e3e41", bold = true, fg = "#ffffff" })
hi(0, "BufferVisibleSign", { link = "BufferVisible" })
hi(0, "BufferVisibleTarget", { bg = "#626266", bold = true, fg = "#ffffff" })
hi(0, "Changed", { fg = "#b3ffe9" })
hi(0, "CmpItemAbbr", { fg = "#ffffff" })
hi(0, "CmpItemAbbrDeprecated", { link = "Comment" })
hi(0, "CmpItemAbbrMatch", { bold = true })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true })
hi(0, "CmpItemKind", { fg = "#ffffff" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstructor", { link = "Type" })
hi(0, "CmpItemKindEnum", { link = "Structure" })
hi(0, "CmpItemKindEnumMember", { link = "Structure" })
hi(0, "CmpItemKindEvent", { link = "Exception" })
hi(0, "CmpItemKindField", { link = "Structure" })
hi(0, "CmpItemKindFile", { link = "Tag" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindInterface", { link = "Structure" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindModule", { link = "Structure" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindProperty", { link = "Structure" })
hi(0, "CmpItemKindReference", { link = "Tag" })
hi(0, "CmpItemKindSnippet", { link = "Special" })
hi(0, "CmpItemKindStruct", { link = "Structure" })
hi(0, "CmpItemKindText", { link = "Normal" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindUnit", { link = "Special" })
hi(0, "CmpItemKindValue", { link = "Identifier" })
hi(0, "CmpItemKindVariable", { link = "Delimiter" })
hi(0, "CmpItemMenu", { fg = "#ffffff" })
hi(0, "CocCodeLens", { link = "LspCodeLens" })
hi(0, "CocDisabled", { link = "Comment" })
hi(0, "CocFadeOut", { link = "Comment" })
hi(0, "CocMarkdownLink", { fg = "#a1c3ff" })
hi(0, "CocMenuSel", { bg = "#626266" })
hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
hi(0, "CocSearch", { fg = "#a1c3ff" })
hi(0, "CocSelectedText", { fg = "#ffe1a6" })
hi(0, "ColorColumn", { bg = "#626266" })
hi(0, "Comment", { fg = "#adadad" })
hi(0, "Conceal", { fg = "#a3ebff" })
hi(0, "Constant", { fg = "#e3beff" })
hi(0, "CurSearch", { bg = "#ffe1a6", fg = "#1c1c1f" })
hi(0, "Cursor", { bg = "#ffffff", fg = "#1c1c1f" })
hi(0, "CursorColumn", { bg = "#3e3e41" })
hi(0, "CursorLine", { bg = "#3e3e41" })
hi(0, "CursorLineFold", { fg = "#626266" })
hi(0, "CursorLineNr", { bold = true, fg = "#bfbcff" })
hi(0, "CursorLineSign", { fg = "#626266" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#e0ffbb" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { link = "Title" })
hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
hi(0, "DapUILineNumber", { link = "Title" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#ffbda5" })
hi(0, "DapUIScope", { link = "Title" })
hi(0, "DapUISource", { link = "Directory" })
hi(0, "DapUIStoppedThread", { link = "Title" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
hi(0, "DapUIWatchesValue", { link = "String" })
hi(0, "DashboardCenter", { link = "Delimiter" })
hi(0, "DashboardFooter", { link = "Comment" })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortCut", { link = "WarningMsg" })
hi(0, "Definitions", { fg = "#e0ffbb" })
hi(0, "DefinitionsIcon", { fg = "#a3ebff" })
hi(0, "Delimiter", { fg = "#ffbda5" })
hi(0, "DiagnosticDeprecated", { sp = "#ffbada", strikethrough = true })
hi(0, "DiagnosticError", { fg = "#ffbada" })
hi(0, "DiagnosticFloatingError", { bg = "#121215", fg = "#ffbada" })
hi(0, "DiagnosticFloatingHint", { bg = "#121215", fg = "#b3ffe9" })
hi(0, "DiagnosticFloatingInfo", { bg = "#121215", fg = "#a1c3ff" })
hi(0, "DiagnosticFloatingOk", { bg = "#121215", fg = "#e0ffbb" })
hi(0, "DiagnosticFloatingWarn", { bg = "#121215", fg = "#ffe1a6" })
hi(0, "DiagnosticHint", { fg = "#b3ffe9" })
hi(0, "DiagnosticInfo", { fg = "#a1c3ff" })
hi(0, "DiagnosticOk", { fg = "#e0ffbb" })
hi(0, "DiagnosticUnderlineError", { sp = "#ffbada", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#b3ffe9", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#a1c3ff", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#e0ffbb", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ffe1a6", underline = true })
hi(0, "DiagnosticWarn", { fg = "#ffe1a6" })
hi(0, "DiffAdd", { bg = "#3c5a00" })
hi(0, "DiffChange", { bg = "#00735e" })
hi(0, "DiffDelete", { bg = "#5c0036" })
hi(0, "DiffText", { bg = "#755500" })
hi(0, "DiffTextAdd", { link = "DiffAdd" })
hi(0, "Directory", { fg = "#a3ebff" })
hi(0, "EndOfBuffer", { fg = "#626266" })
hi(0, "Error", { bg = "#5c0036" })
hi(0, "ErrorMsg", { fg = "#ffbada" })
hi(0, "FinderParam", { fg = "#ffe1a6" })
hi(0, "FinderSpinner", { fg = "#e0ffbb" })
hi(0, "FinderSpinnerBorder", { fg = "#bfbcff" })
hi(0, "FinderSpinnerTitle", { link = "Title" })
hi(0, "FinderVirtText", { fg = "#ffbda5" })
hi(0, "Float", { link = "Constant" })
hi(0, "FloatBorder", { bg = "#121215", fg = "#bfbcff" })
hi(0, "FloatTitle", { bg = "#121215", bold = true, fg = "#bfbcff" })
hi(0, "FoldColumn", { fg = "#626266" })
hi(0, "Folded", { bg = "#121215", fg = "#adadad" })
hi(0, "Function", { fg = "#a3ebff" })
hi(0, "FzfLuaBufFlagAlt", { link = "Special" })
hi(0, "FzfLuaBufFlagCur", { link = "CursorLineNr" })
hi(0, "FzfLuaBufNr", { link = "DiagnosticHint" })
hi(0, "FzfLuaHeaderBind", { link = "DiagnosticWarn" })
hi(0, "FzfLuaHeaderText", { link = "DiagnosticInfo" })
hi(0, "FzfLuaLiveSym", { link = "DiagnosticHint" })
hi(0, "FzfLuaPathColNr", { link = "DiagnosticHint" })
hi(0, "FzfLuaPathLineNr", { link = "DiagnosticInfo" })
hi(0, "FzfLuaTabMarker", { link = "DiagnosticHint" })
hi(0, "FzfLuaTabTitle", { link = "Title" })
hi(0, "FzfLuaTitle", { link = "FloatTitle" })
hi(0, "GitSignsAdd", { fg = "#e0ffbb" })
hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
hi(0, "GitSignsChange", { fg = "#ffe1a6" })
hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
hi(0, "GitSignsDelete", { fg = "#ffbada" })
hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
hi(0, "GitSignsUntracked", { fg = "#a3ebff" })
hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
hi(0, "HelpviewCode", { bg = "#121215" })
hi(0, "HelpviewCodeLanguage", { bg = "#121215" })
hi(0, "HelpviewHeading1", { link = "@markup.heading.1" })
hi(0, "HelpviewHeading2", { link = "@markup.heading.2" })
hi(0, "HelpviewHeading3", { link = "@markup.heading.3" })
hi(0, "HelpviewHeading4", { link = "@markup.heading.4" })
hi(0, "HelpviewInlineCode", { bg = "#121215" })
hi(0, "HelpviewMentionlink", { fg = "#bfbcff", underline = true })
hi(0, "HelpviewOptionlink", { fg = "#ffe1a6", underline = true })
hi(0, "HelpviewTaglink", { bold = true, fg = "#bfbcff" })
hi(0, "HelpviewTitle", { link = "Title" })
hi(0, "HopNextKey", { bold = true, fg = "#e0ffbb", nocombine = true })
hi(0, "HopNextKey1", { bold = true, fg = "#ffbda5", nocombine = true })
hi(0, "HopNextKey2", { bold = true, fg = "#d6d6d6", nocombine = true })
hi(0, "HopPreview", { bold = true, fg = "#ffe1a6", nocombine = true })
hi(0, "HopUnmatched", { fg = "#626266" })
hi(0, "HydraAmaranth", { fg = "#e3beff" })
hi(0, "HydraBlue", { fg = "#a3ebff" })
hi(0, "HydraHint", { link = "NormalFloat" })
hi(0, "HydraPink", { fg = "#ffbda5" })
hi(0, "HydraRed", { fg = "#ffbada" })
hi(0, "HydraTeal", { fg = "#b3ffe9" })
hi(0, "Identifier", { fg = "#ffe1a6" })
hi(0, "Ignore", {})
hi(0, "IncSearch", { bg = "#ffe1a6", fg = "#1c1c1f" })
hi(0, "IndentBlanklineChar", { fg = "#626266", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#bfbcff", nocombine = true })
hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#bfbcff", underline = true })
hi(0, "IndentBlanklineIndent1", { fg = "#a1c3ff", nocombine = true })
hi(0, "IndentBlanklineIndent2", { fg = "#b3ffe9", nocombine = true })
hi(0, "IndentBlanklineIndent3", { fg = "#ffe1a6", nocombine = true })
hi(0, "IndentBlanklineIndent4", { fg = "#ffbada", nocombine = true })
hi(0, "IndentBlanklineIndent5", { fg = "#a3ebff", nocombine = true })
hi(0, "IndentBlanklineIndent6", { fg = "#e0ffbb", nocombine = true })
hi(0, "IndentBlanklineIndent7", { fg = "#ffbda5", nocombine = true })
hi(0, "IndentBlanklineIndent8", { fg = "#e3beff", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "LSOutlinePreviewBorder", { fg = "#bfbcff" })
hi(0, "LazyButton", { bg = "#3e3e41" })
hi(0, "LazyButtonActive", { bg = "#626266" })
hi(0, "LazyDimmed", { link = "Comment" })
hi(0, "LazyH1", { bg = "#626266", bold = true, fg = "#bfbcff" })
hi(0, "LeapBackdrop", { link = "Comment" })
hi(0, "LeapLabel", { bold = true, fg = "#ffe1a6", nocombine = true })
hi(0, "LeapLabelSelected", { bold = true, fg = "#b3ffe9", nocombine = true })
hi(0, "LeapMatch", { bold = true, fg = "#e0ffbb", nocombine = true, underline = true })
hi(0, "LineNr", { fg = "#626266" })
hi(0, "LspCodeLens", { link = "Comment" })
hi(0, "LspCodeLensSeparator", { link = "Comment" })
hi(0, "LspReferenceText", { bg = "#626266" })
hi(0, "LspSagaAutoPreview", { fg = "#a1c3ff" })
hi(0, "LspSagaBorderTitle", { link = "FloatTitle" })
hi(0, "LspSagaCodeActionBorder", { fg = "#bfbcff" })
hi(0, "LspSagaCodeActionContent", { fg = "#ffffff" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#a3ebff" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#bfbcff" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#bfbcff" })
hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
hi(0, "LspSagaDiagnosticSource", { fg = "#ffbda5" })
hi(0, "LspSagaFinderSelection", { fg = "#b3ffe9" })
hi(0, "LspSagaHoverBorder", { fg = "#bfbcff" })
hi(0, "LspSagaLspFinderBorder", { fg = "#bfbcff" })
hi(0, "LspSagaRenameBorder", { fg = "#bfbcff" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#bfbcff" })
hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
hi(0, "MarkviewPalette0", { bg = "#1c1c1f", fg = "#bfbcff" })
hi(0, "MarkviewPalette0Bg", { bg = "#1c1c1f" })
hi(0, "MarkviewPalette0Fg", { fg = "#bfbcff" })
hi(0, "MarkviewPalette0Sign", { fg = "#bfbcff" })
hi(0, "MarkviewPalette1", { bg = "#5c0036", fg = "#ffbada" })
hi(0, "MarkviewPalette1Bg", { bg = "#5c0036" })
hi(0, "MarkviewPalette1Fg", { fg = "#ffbada" })
hi(0, "MarkviewPalette1Sign", { fg = "#ffbada" })
hi(0, "MarkviewPalette2", { bg = "#6a1d00", fg = "#ffbda5" })
hi(0, "MarkviewPalette2Bg", { bg = "#6a1d00" })
hi(0, "MarkviewPalette2Fg", { fg = "#ffbda5" })
hi(0, "MarkviewPalette2Sign", { fg = "#ffbda5" })
hi(0, "MarkviewPalette3", { bg = "#755500", fg = "#ffe1a6" })
hi(0, "MarkviewPalette3Bg", { bg = "#755500" })
hi(0, "MarkviewPalette3Fg", { fg = "#ffe1a6" })
hi(0, "MarkviewPalette3Sign", { fg = "#ffe1a6" })
hi(0, "MarkviewPalette4", { bg = "#3c5a00", fg = "#e0ffbb" })
hi(0, "MarkviewPalette4Bg", { bg = "#3c5a00" })
hi(0, "MarkviewPalette4Fg", { fg = "#e0ffbb" })
hi(0, "MarkviewPalette4Sign", { fg = "#e0ffbb" })
hi(0, "MarkviewPalette5", { bg = "#00735e", fg = "#b3ffe9" })
hi(0, "MarkviewPalette5Bg", { bg = "#00735e" })
hi(0, "MarkviewPalette5Fg", { fg = "#b3ffe9" })
hi(0, "MarkviewPalette5Sign", { fg = "#b3ffe9" })
hi(0, "MarkviewPalette6", { bg = "#006b81", fg = "#a3ebff" })
hi(0, "MarkviewPalette6Bg", { bg = "#006b81" })
hi(0, "MarkviewPalette6Fg", { fg = "#a3ebff" })
hi(0, "MarkviewPalette6Sign", { fg = "#a3ebff" })
hi(0, "MarkviewPalette7", { bg = "#001166", fg = "#a1c3ff" })
hi(0, "MarkviewPalette7Bg", { bg = "#001166" })
hi(0, "MarkviewPalette7Fg", { fg = "#a1c3ff" })
hi(0, "MarkviewPalette7Sign", { fg = "#a1c3ff" })
hi(0, "MasonError", { fg = "#ffbada" })
hi(0, "MasonHeader", { bg = "#a3ebff", bold = true, fg = "#1c1c1f" })
hi(0, "MasonHeaderSecondary", { bg = "#a1c3ff", bold = true, fg = "#1c1c1f" })
hi(0, "MasonHeading", { link = "Bold" })
hi(0, "MasonHighlight", { fg = "#bfbcff" })
hi(0, "MasonHighlightBlock", { bg = "#bfbcff", fg = "#1c1c1f" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#a3ebff", fg = "#1c1c1f" })
hi(0, "MasonHighlightSecondary", { fg = "#a3ebff" })
hi(0, "MasonLink", { link = "MasonHighlight" })
hi(0, "MasonMuted", { link = "Comment" })
hi(0, "MasonMutedBlock", { bg = "#626266", fg = "#1c1c1f" })
hi(0, "MasonMutedBlockBold", { bg = "#626266", bold = true, fg = "#1c1c1f" })
hi(0, "MatchParen", { bg = "#626266", bold = true })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCmdlinePeekBorder", { link = "FloatBorder" })
hi(0, "MiniCmdlinePeekLineNr", { link = "DiagnosticSignWarn" })
hi(0, "MiniCmdlinePeekNormal", { link = "NormalFloat" })
hi(0, "MiniCmdlinePeekSep", { link = "SignColumn" })
hi(0, "MiniCmdlinePeekSign", { link = "DiagnosticSignHint" })
hi(0, "MiniCmdlinePeekTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { link = "LspSignatureActiveParameter" })
hi(0, "MiniCompletionDeprecated", { link = "DiagnosticDeprecated" })
hi(0, "MiniCompletionInfoBorderOutdated", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniDiffOverAdd", { link = "DiffAdd" })
hi(0, "MiniDiffOverChange", { link = "DiffText" })
hi(0, "MiniDiffOverChangeBuf", { link = "MiniDiffOverChange" })
hi(0, "MiniDiffOverContext", { link = "DiffChange" })
hi(0, "MiniDiffOverDelete", { link = "DiffDelete" })
hi(0, "MiniDiffSignAdd", { link = "diffAdded" })
hi(0, "MiniDiffSignChange", { link = "diffChanged" })
hi(0, "MiniDiffSignDelete", { link = "diffRemoved" })
hi(0, "MiniFilesBorder", { link = "FloatBorder" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#ffffff" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { link = "FloatTitle" })
hi(0, "MiniFilesTitleFocused", { bg = "#121215", bold = true, fg = "#ffffff" })
hi(0, "MiniHipatternsFixme", { bg = "#ffbada", bold = true, fg = "#1c1c1f" })
hi(0, "MiniHipatternsHack", { bg = "#ffe1a6", bold = true, fg = "#1c1c1f" })
hi(0, "MiniHipatternsNote", { bg = "#b3ffe9", bold = true, fg = "#1c1c1f" })
hi(0, "MiniHipatternsTodo", { bg = "#a1c3ff", bold = true, fg = "#1c1c1f" })
hi(0, "MiniIconsAzure", { fg = "#a3ebff" })
hi(0, "MiniIconsBlue", { fg = "#a1c3ff" })
hi(0, "MiniIconsCyan", { fg = "#b3ffe9" })
hi(0, "MiniIconsGreen", { fg = "#e0ffbb" })
hi(0, "MiniIconsGrey", { fg = "#ffffff" })
hi(0, "MiniIconsOrange", { fg = "#ffbda5" })
hi(0, "MiniIconsPurple", { fg = "#e3beff" })
hi(0, "MiniIconsRed", { fg = "#ffbada" })
hi(0, "MiniIconsYellow", { fg = "#ffe1a6" })
hi(0, "MiniIndentscopeSymbol", { fg = "#bfbcff" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#ffbada" })
hi(0, "MiniJump", { sp = "#bfbcff", undercurl = true })
hi(0, "MiniJump2dDim", { fg = "#626266" })
hi(0, "MiniJump2dSpot", { bg = "#060608", bold = true, fg = "#ffffff", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#060608", fg = "#ffffff", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
hi(0, "MiniMapNormal", { bg = "#121215", fg = "#adadad" })
hi(0, "MiniMapSymbolCount", { fg = "#adadad" })
hi(0, "MiniMapSymbolLine", { fg = "#bfbcff" })
hi(0, "MiniMapSymbolView", { fg = "#bfbcff" })
hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
hi(0, "MiniNotifyLspProgress", { link = "MiniNotifyNormal" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickBorderText", { link = "FloatTitle" })
hi(0, "MiniPickCursor", { blend = 100, nocombine = true })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniPickMatchMarked", { link = "Visual" })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { link = "MiniPickMatchRanges" })
hi(0, "MiniPickPromptCaret", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniPickPromptPrefix", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniSnippetsCurrent", { sp = "#ffe1a6", underdouble = true })
hi(0, "MiniSnippetsCurrentReplace", { sp = "#ffbada", underdouble = true })
hi(0, "MiniSnippetsFinal", { sp = "#e0ffbb", underdouble = true })
hi(0, "MiniSnippetsUnvisited", { sp = "#b3ffe9", underdouble = true })
hi(0, "MiniSnippetsVisited", { sp = "#a1c3ff", underdouble = true })
hi(0, "MiniStarterCurrent", { link = "MiniStarterItem" })
hi(0, "MiniStarterFooter", { link = "Comment" })
hi(0, "MiniStarterHeader", { bold = true, fg = "#bfbcff" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { link = "Normal" })
hi(0, "MiniStarterItemBullet", { fg = "#adadad" })
hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#ffe1a6" })
hi(0, "MiniStarterQuery", { bold = true, fg = "#e0ffbb" })
hi(0, "MiniStarterSection", { fg = "#e3beff" })
hi(0, "MiniStatuslineDevinfo", { bg = "#3e3e41", fg = "#d6d6d6" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#1c1c1f", fg = "#d6d6d6" })
hi(0, "MiniStatuslineInactive", { link = "StatusLineNC" })
hi(0, "MiniStatuslineModeCommand", { bg = "#ffe1a6", bold = true, fg = "#1c1c1f" })
hi(0, "MiniStatuslineModeInsert", { bg = "#a3ebff", bold = true, fg = "#1c1c1f" })
hi(0, "MiniStatuslineModeNormal", { bg = "#ffffff", bold = true, fg = "#1c1c1f" })
hi(0, "MiniStatuslineModeOther", { bg = "#b3ffe9", bold = true, fg = "#1c1c1f" })
hi(0, "MiniStatuslineModeReplace", { bg = "#ffbada", bold = true, fg = "#1c1c1f" })
hi(0, "MiniStatuslineModeVisual", { bg = "#e0ffbb", bold = true, fg = "#1c1c1f" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#1c1c1f", bold = true, fg = "#bfbcff" })
hi(0, "MiniTablineFill", { link = "MiniTablineCurrent" })
hi(0, "MiniTablineHidden", { bg = "#121215", fg = "#d6d6d6" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#bfbcff", bold = true, fg = "#1c1c1f" })
hi(0, "MiniTablineModifiedHidden", { bg = "#d6d6d6", fg = "#121215" })
hi(0, "MiniTablineModifiedVisible", { bg = "#d6d6d6", bold = true, fg = "#121215" })
hi(0, "MiniTablineTabpagesection", { bg = "#e0ffbb", bold = true, fg = "#1c1c1f" })
hi(0, "MiniTablineTrunc", { bg = "#121215", bold = true, fg = "#bfbcff" })
hi(0, "MiniTablineVisible", { bg = "#121215", bold = true, fg = "#d6d6d6" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#ffbada" })
hi(0, "MiniTestPass", { bold = true, fg = "#e0ffbb" })
hi(0, "MiniTrailspace", { bg = "#5c0036" })
hi(0, "ModeMsg", { fg = "#e0ffbb" })
hi(0, "MoreMsg", { fg = "#a3ebff" })
hi(0, "MsgArea", { link = "Normal" })
hi(0, "MsgSeparator", { fg = "#bfbcff" })
hi(0, "NeoTreeDimText", { fg = "#626266" })
hi(0, "NeoTreeDotfile", { fg = "#d6d6d6" })
hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
hi(0, "NeoTreeFadeText2", { fg = "#626266" })
hi(0, "NeoTreeGitAdded", { fg = "#e0ffbb" })
hi(0, "NeoTreeGitConflict", { bold = true, fg = "#ffbda5" })
hi(0, "NeoTreeGitDeleted", { fg = "#ffbada" })
hi(0, "NeoTreeGitModified", { fg = "#ffe1a6" })
hi(0, "NeoTreeGitUnstaged", { fg = "#e3beff" })
hi(0, "NeoTreeGitUntracked", { fg = "#b3ffe9" })
hi(0, "NeoTreeMessage", { bg = "#3e3e41", fg = "#ffffff" })
hi(0, "NeoTreeModified", { fg = "#ffffff" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#bfbcff" })
hi(0, "NeoTreeTabInactive", { fg = "#adadad" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#626266", fg = "#adadad" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#3e3e41", fg = "#3e3e41" })
hi(0, "NeogitCommitViewHeader", { link = "Special" })
hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFold", { link = "FoldColumn" })
hi(0, "NeogitHunkHeader", { fg = "#bfbcff" })
hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#bfbcff" })
hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#a3ebff" })
hi(0, "NoiceConfirmBorder", { fg = "#ffe1a6" })
hi(0, "NonText", { fg = "#626266" })
hi(0, "Normal", { bg = "#1c1c1f", fg = "#ffffff" })
hi(0, "NormalFloat", { bg = "#121215", fg = "#ffffff" })
hi(0, "NormalNC", { link = "Normal" })
hi(0, "NotifyDEBUGBorder", { fg = "#e0ffbb" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBorder", { fg = "#ffbada" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyINFOBorder", { fg = "#a1c3ff" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyTRACEBorder", { fg = "#b3ffe9" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { fg = "#ffe1a6" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#e0ffbb" })
hi(0, "NvimTreeFolderIcon", { fg = "#adadad" })
hi(0, "NvimTreeGitDeleted", { fg = "#ffbada" })
hi(0, "NvimTreeGitDirty", { fg = "#ffe1a6" })
hi(0, "NvimTreeGitMerge", { fg = "#ffbda5" })
hi(0, "NvimTreeGitNew", { fg = "#b3ffe9" })
hi(0, "NvimTreeGitRenamed", { fg = "#e3beff" })
hi(0, "NvimTreeGitStaged", { fg = "#e0ffbb" })
hi(0, "NvimTreeImageFile", { fg = "#ffbda5" })
hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#bfbcff" })
hi(0, "NvimTreeSpecialFile", { fg = "#bfbcff", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#a1c3ff" })
hi(0, "NvimTreeWindowPicker", { bg = "#626266", bold = true, fg = "#ffffff" })
hi(0, "OkMsg", { fg = "#e0ffbb" })
hi(0, "Operator", { fg = "#ffffff" })
hi(0, "OutlineDetail", { fg = "#626266" })
hi(0, "OutlineFoldPrefix", { fg = "#ffe1a6" })
hi(0, "OutlineIndentEvn", { fg = "#adadad" })
hi(0, "OutlineIndentOdd", { fg = "#ffffff" })
hi(0, "Pmenu", { link = "NormalFloat" })
hi(0, "PmenuMatchSel", { blend = 0, bold = true, reverse = true })
hi(0, "PmenuThumb", { bg = "#626266" })
hi(0, "PounceAccept", { bg = "#ffe1a6", bold = true, fg = "#1c1c1f", nocombine = true })
hi(0, "PounceAcceptBest", { bg = "#e0ffbb", bold = true, fg = "#1c1c1f", nocombine = true })
hi(0, "PounceGap", { bg = "#626266", bold = true, fg = "#1c1c1f", nocombine = true })
hi(0, "PounceMatch", { bg = "#ffffff", bold = true, fg = "#1c1c1f", nocombine = true })
hi(0, "PreProc", { fg = "#a1c3ff" })
hi(0, "Question", { fg = "#a3ebff" })
hi(0, "QuickFixLine", { bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#a3ebff" })
hi(0, "RainbowDelimiterCyan", { fg = "#b3ffe9" })
hi(0, "RainbowDelimiterGreen", { fg = "#e0ffbb" })
hi(0, "RainbowDelimiterOrange", { fg = "#ffbda5" })
hi(0, "RainbowDelimiterRed", { fg = "#ffbada" })
hi(0, "RainbowDelimiterViolet", { fg = "#e3beff" })
hi(0, "RainbowDelimiterYellow", { fg = "#ffe1a6" })
hi(0, "References", { fg = "#e0ffbb" })
hi(0, "ReferencesIcon", { fg = "#a3ebff" })
hi(0, "Removed", { fg = "#ffbada" })
hi(0, "RenderMarkdownBullet", { fg = "#bfbcff" })
hi(0, "RenderMarkdownChecked", { link = "DiagnosticOk" })
hi(0, "RenderMarkdownCode", { bg = "#121215" })
hi(0, "RenderMarkdownCodeInline", { bg = "#121215" })
hi(0, "RenderMarkdownDash", { fg = "#bfbcff" })
hi(0, "RenderMarkdownH1", { fg = "#ffbda5" })
hi(0, "RenderMarkdownH1Bg", { bg = "#6a1d00" })
hi(0, "RenderMarkdownH2", { fg = "#ffe1a6" })
hi(0, "RenderMarkdownH2Bg", { bg = "#755500" })
hi(0, "RenderMarkdownH3", { fg = "#e0ffbb" })
hi(0, "RenderMarkdownH3Bg", { bg = "#3c5a00" })
hi(0, "RenderMarkdownH4", { fg = "#b3ffe9" })
hi(0, "RenderMarkdownH4Bg", { bg = "#00735e" })
hi(0, "RenderMarkdownH5", { fg = "#a3ebff" })
hi(0, "RenderMarkdownH5Bg", { bg = "#006b81" })
hi(0, "RenderMarkdownH6", { fg = "#a1c3ff" })
hi(0, "RenderMarkdownH6Bg", { bg = "#001166" })
hi(0, "RenderMarkdownTodo", { link = "Todo" })
hi(0, "RenderMarkdownUnchecked", { link = "DiagnosticWarn" })
hi(0, "Search", { bg = "#bfbcff", fg = "#1c1c1f" })
hi(0, "SignColumn", { fg = "#626266" })
hi(0, "SnacksPickerBufFlags", { link = "Comment" })
hi(0, "SnacksPickerDir", { link = "Comment" })
hi(0, "SnacksPickerGitStatusIgnored", { link = "Comment" })
hi(0, "SnacksPickerGitStatusUntracked", { link = "Comment" })
hi(0, "SnacksPickerKeymapRhs", { link = "Comment" })
hi(0, "SnacksPickerListCursorLine", { link = "CursorLine" })
hi(0, "SnacksPickerPathHidden", { link = "Comment" })
hi(0, "SnacksPickerPathIgnored", { link = "Comment" })
hi(0, "SnacksPickerTotals", { link = "Comment" })
hi(0, "SnacksPickerUnselected", { link = "Comment" })
hi(0, "Sneak", { bg = "#ffbda5", fg = "#1c1c1f" })
hi(0, "SneakLabel", { bg = "#ffbda5", bold = true, fg = "#1c1c1f" })
hi(0, "SneakScope", { bg = "#ffffff", fg = "#1c1c1f" })
hi(0, "SnippetTabstop", { bg = "#755500" })
hi(0, "SnippetTabstopActive", { bg = "#3c5a00" })
hi(0, "Special", { fg = "#b3ffe9" })
hi(0, "SpecialKey", { fg = "#626266" })
hi(0, "SpellBad", { sp = "#ffbada", undercurl = true })
hi(0, "SpellCap", { sp = "#b3ffe9", undercurl = true })
hi(0, "SpellLocal", { sp = "#ffe1a6", undercurl = true })
hi(0, "SpellRare", { sp = "#a1c3ff", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#ffffff" })
hi(0, "StatusLine", { bg = "#1c1c1f", fg = "#d6d6d6" })
hi(0, "StatusLineNC", { bg = "#121215", fg = "#d6d6d6" })
hi(0, "StdoutMsg", { link = "MsgArea" })
hi(0, "String", { fg = "#e0ffbb" })
hi(0, "Substitute", { bg = "#a1c3ff", fg = "#1c1c1f" })
hi(0, "TabLine", { bg = "#121215", fg = "#d6d6d6" })
hi(0, "TabLineSel", { bg = "#121215", fg = "#bfbcff" })
hi(0, "TargetFileName", { fg = "#ffffff" })
hi(0, "TelescopeBorder", { fg = "#bfbcff" })
hi(0, "TelescopeMatching", { bold = true })
hi(0, "TelescopeMultiSelection", { bg = "#626266" })
hi(0, "TelescopeSelection", { bg = "#3e3e41" })
hi(0, "TermCursorNC", { reverse = true })
hi(0, "Title", { fg = "#bfbcff" })
hi(0, "Todo", { bg = "#1c1c1f", bold = true, fg = "#bfbcff" })
hi(0, "TroubleCount", { bold = true, fg = "#bfbcff" })
hi(0, "TroubleFoldIcon", { bold = true, fg = "#bfbcff" })
hi(0, "TroubleIndent", { fg = "#626266" })
hi(0, "TroubleLocation", { fg = "#d6d6d6" })
hi(0, "TroubleSignError", { link = "DiagnosticError" })
hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
hi(0, "TroubleText", { fg = "#ffffff" })
hi(0, "TroubleTextError", { link = "TroubleText" })
hi(0, "TroubleTextHint", { link = "TroubleText" })
hi(0, "TroubleTextInformation", { link = "TroubleText" })
hi(0, "TroubleTextWarning", { link = "TroubleText" })
hi(0, "Type", { fg = "#ffffff" })
hi(0, "VertSplit", { fg = "#bfbcff" })
hi(0, "Visual", { bg = "#626266" })
hi(0, "VisualNOS", { bg = "#3e3e41" })
hi(0, "WarningMsg", { fg = "#ffe1a6" })
hi(0, "WhichKey", { fg = "#b3ffe9" })
hi(0, "WhichKeyBorder", { link = "FloatBorder" })
hi(0, "WhichKeyDesc", { fg = "#ffffff" })
hi(0, "WhichKeyFloat", { bg = "#121215", fg = "#ffffff" })
hi(0, "WhichKeyGroup", { fg = "#ffbada" })
hi(0, "WhichKeySeparator", { fg = "#e0ffbb" })
hi(0, "WhichKeyValue", { link = "Comment" })
hi(0, "Whitespace", { fg = "#626266" })
hi(0, "WinBar", { link = "StatusLine" })
hi(0, "WinBarNC", { link = "StatusLineNC" })
hi(0, "WinSeparator", { fg = "#bfbcff" })
hi(0, "diffAdded", { fg = "#e0ffbb" })
hi(0, "diffChanged", { fg = "#b3ffe9" })
hi(0, "diffFile", { fg = "#ffe1a6" })
hi(0, "diffLine", { fg = "#a1c3ff" })
hi(0, "diffRemoved", { fg = "#ffbada" })
hi(0, "gitcommitBranch", { bold = true, fg = "#ffbda5" })
hi(0, "gitcommitComment", { link = "Comment" })
hi(0, "gitcommitDiscarded", { link = "Comment" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#ffe1a6" })
hi(0, "gitcommitDiscardedType", { fg = "#a3ebff" })
hi(0, "gitcommitHeader", { link = "Title" })
hi(0, "gitcommitOverflow", { fg = "#ffe1a6" })
hi(0, "gitcommitSelected", { link = "Comment" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#e0ffbb" })
hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitSummary", { fg = "#e0ffbb" })
hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitUntracked", { link = "Comment" })
hi(0, "gitcommitUntrackedFile", { fg = "#b3ffe9" })
hi(0, "lCursor", { bg = "#ffffff", fg = "#1c1c1f" })
hi(0, "markdownH1", { link = "@markup.heading.1" })
hi(0, "markdownH2", { link = "@markup.heading.2" })
hi(0, "markdownH3", { link = "@markup.heading.3" })
hi(0, "markdownH4", { link = "@markup.heading.4" })
hi(0, "markdownH5", { link = "@markup.heading.5" })
hi(0, "markdownH6", { link = "@markup.heading.6" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#060608"
g.terminal_color_1 = "#ffbada"
g.terminal_color_2 = "#e0ffbb"
g.terminal_color_3 = "#ffe1a6"
g.terminal_color_4 = "#a3ebff"
g.terminal_color_5 = "#e3beff"
g.terminal_color_6 = "#b3ffe9"
g.terminal_color_7 = "#adadad"
g.terminal_color_8 = "#626266"
g.terminal_color_9 = "#ffbada"
g.terminal_color_10 = "#e0ffbb"
g.terminal_color_11 = "#ffe1a6"
g.terminal_color_12 = "#a3ebff"
g.terminal_color_13 = "#e3beff"
g.terminal_color_14 = "#b3ffe9"
g.terminal_color_15 = "#ffffff"
